### ISSUE TITLE
Change type signature of getColumn

### ISSUE THREAD

**Issue by MartinSStewart** [tortus/elm-array-2d#3]
Currently `getColumn` looks like this `Int -> Array2D a -> Array (Maybe a)`. I think this is unintuitive. Shouldn't it be `Int -> Array2D a -> Maybe (Array a)`? The former seems to imply that you can get something back that looks like this `[ Just 0, Nothing, Just 1 ]`.

**Comment by wmakley** [comment]
Hey I'm happy that you're interested in this library! I think the type signature was because the storage is row-based, not column based. Basically, it is getting the nth cell of each row, which will be 'Maybe a'. I'm sure I didn't bother re-working it, because I didn't use it. If you want, please submit a PR to change that function and I'd be happy to push a new version.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by wmakley** [comment]
I think I successfully published version 3.0.0. Let me know if you have any issues!

**Comment by MartinSStewart** [comment]
Looks good to go, thanks!
